version: "3.7"
services:
  master:
    image: alpine:latest
    container_name: master01
    hostname: master01
    stdin_open: true
    tty: true
    command : >
      /bin/sh -c "apk update
      &&  apk add ansible openssh-server openssh
      && /bin/sh
      &&  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      &&  sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
      &&  echo 'root:toor' | chpasswd
      &&  /usr/sbin/sshd -D"
    volumes:
      - ansible_vol:/var/ans
      - ./files/:/files/
  jenkins:
    image: imagejenkinstp6:latest
    container_name: jenkins
    hostname: jenkins
    stdin_open: true
    tty: true
    ports: 
      - "8098:8080"
      - "50000:50000"
  pythonubuntu:
    links:
      - master
    image: ubuntu
    container_name: pythonubuntu
    hostname: pythonubuntu
    stdin_open: true
    tty: true
    command : >
      bash -c "apt update && apt upgrade -y 
      &&  DEBIAN_FRONTEND=noninteractive 
      &&  mkdir /run/sshd 
      &&  apt install -y apt --no-install-recommends python3 openssh-server sudo
      &&  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      &&  sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
      &&  echo 'root:toor' | chpasswd 
      &&  /usr/sbin/sshd -D" 
    expose: 
      - 22
    volumes:
     - ansible_vol:/var/ans
  dbubuntu:
    links:
      - master
    image: ubuntu
    container_name: dbubuntu
    hostname: dbubuntu
    stdin_open: true
    tty: true
    command : >
      bash -c "apt update && apt upgrade -y 
      &&  DEBIAN_FRONTEND=noninteractive 
      &&  mkdir /run/sshd 
      &&  apt install -y apt --no-install-recommends python3 openssh-server sudo
      &&  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      &&  sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
      &&  echo 'root:toor' | chpasswd 
      && /usr/sbin/sshd -D"
    expose: 
      - 22
    ports:
      - 3308:3306
    volumes:
     - ansible_vol:/var/ans
  pythoncentos:
    links:
      - master
    image: centos:7
    container_name: pythoncentos
    hostname: pythoncentos
    stdin_open: true
    tty: true
    command : >
      /bin/sh -c "yum update -y 
      &&  yum install -y openssh-server python wget
      &&  wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
      &&  chmod +x mariadb_repo_setup 
      &&  ./mariadb_repo_setup
      &&  rm mariadb_repo_setup
      &&  yum clean all 
      &&  sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config 
      &&  echo 'root:toor' | chpasswd 
      &&  ssh-keygen -A
      && /usr/sbin/sshd -D"        
    expose:
      - 22
    volumes:
     - ansible_vol:/var/ans
  dbcentos:
    links:
      - master
    image: centos:7
    container_name: dbcentos
    hostname: dbcentos
    stdin_open: true
    tty: true
    command : >
      /bin/sh -c "yum update -y 
      &&  yum install -y openssh-server python 
      &&  yum clean all 
      &&  sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config 
      &&  echo 'root:toor' | chpasswd 
      &&  ssh-keygen -A
      && /usr/sbin/sshd -D"         
    expose:
      - 22
    ports:
      - 3307:3306
    volumes:
     - ansible_vol:/var/ans
volumes:
  ansible_vol:        
